### ISSUE TITLE
Permisson for this repo

### ISSUE THREAD

**Issue by xarbit** [flathub/org.gnome.FeedReader#1]
Thanks for adding FeedReader to Flathub!
I am the maintainer of FeedReader Flatpak, is it possible to get permission for this repo? 

Thanks.

Jason

**Comment by TingPing** [comment]
Added

**Comment by xarbit** [comment]
Thank you!

**Comment by bilelmoussaoui** [comment]
Hey @TingPing Can you please add me, @brendanlong and @jangernert? Thanks!

**Comment by barthalion** [comment]
Invitations sent.
