### ISSUE TITLE
Deprecation message is misleading as there is no replacement

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.gnome.FeedReader#17]
I just got the message that Feedreader was deprecated but there is no "newsflash" available.

**Comment by jangernert** [comment]
I originally wanted to wait until NewsFlash was in flathub. But it's been already 23 days I'm basically ready and waiting for a flathub maintainer to help me integrate API secrets: https://github.com/flathub/flathub/pull/1537#issuecomment-633477553

**Comment by hfiguiere** [comment]
Do I understand that it doesn't support local mode and will require some sort of account on some sort of service?

**Comment by jangernert** [comment]
No, it does support that as well. Some of the services are not (yet) supported.

**Comment by jangernert** [comment]
But it is also perfectly fine to continue using FeedReader.

**Comment by hfiguiere** [comment]
ah ok, that was unclear from the readme since it said:

> A modern feed reader designed for the GNOME desktop. NewsFlash is a program designed to complement an already existing web-based RSS reader account.

Thanks!

**Comment by hfiguiere** [comment]
> But it is also perfectly fine to continue using FeedReader.

Sure but given the amount of segfaults I get with it.... (issues have been filed FWIW)

**Comment by hfiguiere** [comment]
to be clear, I look forward to Newsflash.

**Comment by jangernert** [comment]
This means the application is designed around the idea of syncing with services. And all design decisions are made with that in mind. Even if having full control (like it is the case with Local RSS) would make things easier or more powerful.

For example: With only Local RSS it would be possible to update feeds 1 by 1 and update the GUI accordingly. NewsFlash (and FeedReader) can't do that.

**Comment by hfiguiere** [comment]
And I installed the test build and I can't see where I can import from Feedreader... :-/

**Comment by hfiguiere** [comment]
https://gitlab.com/news-flash/news_flash_gtk/-/issues/91
